service: apollo-lambda
provider:
  name: aws
  runtime: nodejs16.x
  httpApi:
    cors: true
functions:
  graphql:
    handler: src/server.handler
    events:
      - httpApi:
          path: /graphql
          method: POST
      - httpApi:
          path: /graphql
          method: GET
