service: roots-api
provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, staging}
  httpApi:
    cors: true
functions:
  graphql:
    handler: src/handler.handler
    events:
      - httpApi:
          path: /graphql
          method: POST
      - httpApi:
          path: /graphql
          method: GET
